
language: erlang

matrix:

  include:

    - os: linux
      dist: xenial
      otp_release: 22.3

    - os: linux
      dist: xenial
      otp_release: 21.3

    - os: linux
      dist: xenial
      otp_release: 20.3

    - os: linux
      dist: xenial
      otp_release: 19.3

    - os: osx
      language: generic

before_script:

- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang|| true; fi

- curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3 && chmod +x rebar3

script:
    - ./rebar3 compile

after_success:
    - ./rebar3 ct
